=== denjai/TU-Plovdiv/Semester7/XML_others/uni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 (http://www.altova.com) by Ivan Ivanov (Ivanov Ltd.) -->
<!--W3C Schema generated by XMLSpy v2010 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="subject">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="XML technologies"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="semester">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="leten"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Gosho"/>
				<xs:enumeration value="Ivan"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="group">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="42"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="fam">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Genchev"/>
				<xs:enumeration value="Petrov"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="deptID" type="xs:integer"/>
	<xs:element name="Uni">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StudentGroup"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StudentGroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Lection"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Student">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="fam"/>
				<xs:element ref="deptID"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Prof">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:element ref="fam"/>
				<xs:element ref="EGN"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Student"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Lection">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Prof"/>
				<xs:element ref="subject"/>
				<xs:element ref="semester"/>
				<xs:element ref="group"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EGN" type="xs:integer"/>
</xs:schema>

=== denjai/TU-Plovdiv/Semester7/XML_others/zad3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Uni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\DOCUME~1\XMLTEC~1\Desktop\XML\uni.xsd">
	<StudentGroup>
		<Name>
			<Student>
				<name>Ivan</name>
				<fam>Petrov</fam>
				<deptID>123</deptID>
			</Student>
		</Name>
		<Lection>
			<Prof>
				<name>Gosho</name>
				<fam>Genchev</fam>
				<EGN>8899887766</EGN>
			</Prof>
			<subject>XML technologies</subject>
			<semester>leten</semester>
			<group>42</group>
		</Lection>
	</StudentGroup>
</Uni>
